"""I/O operations — AWS, CSV loading, cache management, thumbnails, JSON writing."""

import csv
import hashlib
import json
import re
import subprocess
import sys
import time

from pipeline.constants import (
    DATA_DIR, ASSETS_DIR, CARD_ASSETS_DIR, CARD_PNG_ASSETS_DIR, ARTWORK_DIR, CARD_SCREENSHOTS_DIR,
    RAW_CACHE, CARDS_CSV, COMMANDERS_CSV, TOKENS_CSV, CARDLIST_ASSET,
    DYNAMO_TABLE, DYNAMO_REGION, PATRON_MAP, COMMANDER_RENAMES,
    COMMISSIONED_ART_TYPES,
)
from pipeline.cleaning import normalize_commander


# ─── Thumbnail Generation ──────────────────────────────────────

def _resize_image(source, target, max_width, quality=85):
    """Resize a source image to max_width, save as JPEG. Returns True on success."""
    try:
        from PIL import Image
        img = Image.open(source)
        if img.width > max_width:
            ratio = max_width / img.width
            new_size = (max_width, int(img.height * ratio))
            img = img.resize(new_size, Image.LANCZOS)
        img = img.convert("RGB")
        img.save(target, "JPEG", quality=quality)
        return True
    except ImportError:
        try:
            subprocess.run([
                "sips", "-s", "format", "jpeg",
                "-Z", str(max_width), str(source),
                "--out", str(target),
            ], check=True, capture_output=True)
            return True
        except (FileNotFoundError, subprocess.CalledProcessError):
            return False


def _resize_png_rgba(source, target, max_width):
    """Resize an RGBA source PNG to max_width, preserving alpha. Returns True
    on success. Used to produce transparent card art for hover popups and
    inline article images. Falls back to skipping the file if PIL is missing —
    JPGs are already generated by _resize_image so hover still works."""
    try:
        from PIL import Image
    except ImportError:
        return False
    img = Image.open(source)
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    if img.width > max_width:
        ratio = max_width / img.width
        new_size = (max_width, int(img.height * ratio))
        img = img.resize(new_size, Image.LANCZOS)
    img.save(target, "PNG", optimize=False)
    return True


def _art_slug(name):
    """Convert a name like 'Elber, Jungle Emissary' to 'elber-jungle-emissary'."""
    return name.lower().replace(" ", "-").replace(",", "").replace("'", "")


def _file_hash(path):
    """SHA-1 of a file's bytes, used to detect when source art actually changed.

    We hash content rather than compare mtimes because git does not preserve
    mtimes: a fresh CI checkout stamps every file with the checkout time, so an
    mtime comparison can never tell whether the underlying art changed. See the
    manifest logic in generate_thumbnails().
    """
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def generate_thumbnails():
    """Generate optimized thumbnails for commanders (from Artwork/) and cards (from CardScreenshots/).

    Commander art:  Artwork/<slug>.png → site/assets/commanders/<slug>.jpg  (400px wide)
                    Only processes files whose slug matches a commander in the CSV.
    Card previews:  CardScreenshots/*.png → site/assets/cards/*.jpg  (600px wide)

    Regenerates a thumbnail when its target is missing or the source art's
    content has changed. Change is detected by hashing the source bytes and
    comparing against a committed manifest (site/assets/.thumbnail-src-hashes.json)
    rather than by mtime: git does not preserve mtimes, so in a fresh CI checkout
    every file carries the checkout time and an mtime comparison silently skips
    updated art (it would only ever regenerate brand-new cards). See _file_hash().
    """
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    CARD_ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    CARD_PNG_ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    # Manifest of source-art hashes, keyed by "<kind>:<slug>". Lives under
    # site/assets/ so the daily pipeline's `git add site/assets/` commits it and
    # the next checkout can read it back.
    manifest_path = CARD_PNG_ASSETS_DIR.parent / ".thumbnail-src-hashes.json"
    manifest = {}
    if manifest_path.exists():
        try:
            with open(manifest_path, "r", encoding="utf-8") as f:
                manifest = json.load(f)
        except (json.JSONDecodeError, OSError):
            manifest = {}

    def _needs_regen(key, target, source_hash):
        """Regenerate if the target is missing or the source content changed."""
        return not target.exists() or manifest.get(key) != source_hash

    cmd_count = 0
    card_count = 0
    card_png_count = 0

    # Build set of valid commander slugs from CSV
    commander_slugs = set()
    if COMMANDERS_CSV.exists():
        with open(COMMANDERS_CSV, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                name = normalize_commander(row.get("Name", "").strip())
                if name:
                    commander_slugs.add(_art_slug(name))

    # Commander thumbnails from Artwork/ (only files matching commander names).
    # A slug can have more than one source file (e.g. both executor-ginn.png and
    # executor-ginn.jpg). They share a single .jpg target, so pick one winner
    # deterministically — prefer the PNG master — and skip the rest, otherwise
    # they overwrite each other's manifest entry and regenerate on every run.
    if ARTWORK_DIR.exists() and commander_slugs:
        _ext_priority = {".png": 0, ".jpg": 1, ".jpeg": 1}
        sources = sorted(
            (s for s in ARTWORK_DIR.iterdir()
             if s.suffix.lower() in _ext_priority and s.stem.lower() in commander_slugs),
            key=lambda s: (s.stem.lower(), _ext_priority[s.suffix.lower()], s.name),
        )
        seen_slugs = set()
        for source in sources:
            slug = source.stem.lower()
            if slug in seen_slugs:
                print(f"  (skipping duplicate commander art {source.name}; already have {slug})")
                continue
            seen_slugs.add(slug)
            target = ASSETS_DIR / f"{slug}.jpg"
            src_hash = _file_hash(source)
            key = f"cmd:{slug}"
            if not _needs_regen(key, target, src_hash):
                continue
            if _resize_image(source, target, 400):
                manifest[key] = src_hash
                cmd_count += 1

    # Card thumbnails from CardScreenshots/. Each source PNG produces:
    #   - site/assets/cards/<slug>.jpg          framed card, 600px wide (hover today, OG images)
    #   - site/assets/card-art-png/<slug>.png   same image with alpha preserved, 500px wide
    #     (used by .card-preview hover popup and [[card-img:...]] inline embeds —
    #      transparent corners blend with the dark site background)
    if CARD_SCREENSHOTS_DIR.exists():
        for source in CARD_SCREENSHOTS_DIR.iterdir():
            if source.suffix.lower() not in (".png", ".jpg", ".jpeg"):
                continue
            slug = source.stem.lower()
            src_hash = _file_hash(source)
            jpg_target = CARD_ASSETS_DIR / f"{slug}.jpg"
            jpg_key = f"card-jpg:{slug}"
            if _needs_regen(jpg_key, jpg_target, src_hash):
                if _resize_image(source, jpg_target, 600):
                    manifest[jpg_key] = src_hash
                    card_count += 1
            # PNG with alpha — only meaningful if source has alpha (RGBA PNGs in
            # CardScreenshots/). _resize_png_rgba auto-converts otherwise.
            if source.suffix.lower() == ".png":
                png_target = CARD_PNG_ASSETS_DIR / f"{slug}.png"
                png_key = f"card-png:{slug}"
                if _needs_regen(png_key, png_target, src_hash):
                    if _resize_png_rgba(source, png_target, 500):
                        manifest[png_key] = src_hash
                        card_png_count += 1

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)

    print(f"  Thumbnails: {cmd_count} commander + {card_count} card JPGs + {card_png_count} card PNGs generated")
    if cmd_count == 0 and card_count == 0 and card_png_count == 0:
        print("  (all thumbnails up to date)")


# ─── Card List ───────────────────────────────────────────────────

def write_cardlist():
    """Update site/data/cardlist.json from Formats/FullCardList.asset.

    No-ops gracefully if the asset file is missing.
    """
    from datetime import date

    if not CARDLIST_ASSET.exists():
        print("  (Formats/FullCardList.asset not found, skipping cardlist update)")
        return

    names = []
    in_list = False
    with open(CARDLIST_ASSET, "r") as f:
        for line in f:
            stripped = line.strip()
            if stripped == "_cardNameOrderedList:":
                in_list = True
                continue
            if in_list:
                if stripped.startswith("- "):
                    names.append(stripped[2:])
                else:
                    break

    output_path = DATA_DIR / "cardlist.json"
    _check_cardlist_ids_stable(output_path, names)
    output = {
        "version": date.today().isoformat(),
        "total": len(names),
        "cards": [{"id": i, "name": name} for i, name in enumerate(names)],
        "legacy_names": COMMANDER_RENAMES,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)

    size_kb = output_path.stat().st_size / 1024
    print(f"  Updated cardlist.json: {len(names)} cards ({size_kb:.1f} KB)")


def _check_cardlist_ids_stable(previous_path, names):
    """Fail loudly if an existing card id now points at a different name.

    A card's id is its position in FullCardList.asset's _cardNameOrderedList,
    and deck codes store those ids. The list is therefore append-only: deleting
    or reordering an entry silently re-points every later id at a different
    card, and every deck code minted before the change decodes to the wrong
    deck. A retired card keeps its entry as a placeholder (the Decks page
    already hides names that are not in cards.json). A renamed commander is
    fine as long as the rename is recorded in COMMANDER_RENAMES.
    """
    if not previous_path.exists():
        return
    try:
        with open(previous_path, "r") as f:
            previous = json.load(f)["cards"]
    except (OSError, ValueError, KeyError):
        return

    problems = []
    for prev in previous:
        pid, old_name = prev["id"], prev["name"]
        if pid >= len(names):
            problems.append(f"  id {pid}: '{old_name}' is gone (list shrank to {len(names)})")
        elif names[pid] != old_name and COMMANDER_RENAMES.get(old_name) != names[pid]:
            problems.append(f"  id {pid}: was '{old_name}', now '{names[pid]}'")
    if problems:
        shown = "\n".join(problems[:5])
        more = f"\n  ... and {len(problems) - 5} more" if len(problems) > 5 else ""
        raise SystemExit(
            "cardlist: Formats/FullCardList.asset re-points existing card ids, which "
            "would break every deck code minted before this change:\n"
            f"{shown}{more}\n"
            "The _cardNameOrderedList is append-only. Restore the removed entry at its "
            "original position (keep it as a placeholder for a retired card), or add "
            "the rename to COMMANDER_RENAMES."
        )


# ─── AWS / DynamoDB ─────────────────────────────────────────────

def get_dynamo_table():
    """Create DynamoDB table resource with retry-friendly config."""
    try:
        import boto3
        from botocore.config import Config
    except ImportError:
        print("Error: boto3 is required. Install with: pip install boto3")
        sys.exit(1)

    config = Config(
        retries={"max_attempts": 10, "mode": "adaptive"},
        read_timeout=120,
        connect_timeout=10,
    )
    dynamodb = boto3.resource("dynamodb", region_name=DYNAMO_REGION, config=config)
    return dynamodb.Table(DYNAMO_TABLE)


def scan_all_games(table, cached_game_ids=None):
    """Scan DynamoDB table for all games. Returns list of raw items.

    If cached_game_ids is provided, we still do a full scan (DynamoDB has no
    GSI on datetime), but skip items we've already processed.
    """
    cached_game_ids = cached_game_ids or set()
    items = []
    new_count = 0
    scan_kwargs = {}
    page = 0

    while True:
        page += 1
        try:
            response = table.scan(**scan_kwargs)
        except Exception as e:
            if "ProvisionedThroughputExceededException" in str(type(e).__name__) or "Throughput" in str(e):
                wait = min(2 ** page, 30)
                print(f"    Throttled, waiting {wait}s...")
                time.sleep(wait)
                continue
            raise

        for item in response.get("Items", []):
            gid = item.get("gameid", "")
            if gid not in cached_game_ids:
                items.append(item)
                new_count += 1

        scanned = response.get("ScannedCount", 0)
        print(f"    Page {page}: scanned {scanned} items, {new_count} new so far")

        if "LastEvaluatedKey" not in response:
            break
        scan_kwargs["ExclusiveStartKey"] = response["LastEvaluatedKey"]

    return items


# ─── Reference Data (CSVs) ──────────────────────────────────────

def parse_mentioned_cards(row):
    """Parse the MentionedCards column into a list of card names.

    The column lists cards this one creates or otherwise refers to (the token a
    minion spawns, the spell a commander adds to your hand). It's usually a
    single name today, but accept ';' and ',' separated lists so extra entries
    don't need a pipeline change. Names are not resolved here — the frontend
    matches them against cards.json by slug.
    """
    raw = (row.get("MentionedCards") or "").strip()
    if not raw:
        return []
    parts = [p.strip() for chunk in raw.split(";") for p in chunk.split(",")]
    # dict.fromkeys de-dupes while preserving CSV order
    return list(dict.fromkeys(p for p in parts if p))


def load_cards_csv(path=None, token=False):
    """Load card definitions from intern's CSV.

    ``path`` defaults to the standard-format card list; pass TOKENS_CSV with
    ``token=True`` to load generated cards instead (same columns). Token records
    carry ``"token": True`` so consumers can hide them — they're real cards with
    real stats, but no deck can contain one.
    """
    path = path or CARDS_CSV
    cards = []
    if not path.exists():
        print(f"  Warning: {path} not found, skipping card definitions")
        return cards

    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row.get("Name", "").strip()
            if not name:
                continue

            patron = row.get("Patron", "Neutral").strip()
            cost = row.get("Cost", "")
            attack = row.get("Attack", "")
            speed = row.get("Speed", "")
            health = row.get("Health", "")

            # Build card art filename: "Card Name" → "Card-Name.png"
            art_slug = name.replace(" ", "-").replace(",", "").replace("'", "")
            art_file = f"{art_slug}.png"
            has_art = (CARD_SCREENSHOTS_DIR / art_file).exists() if CARD_SCREENSHOTS_DIR.exists() else False

            # Art/animation metadata for goal tracking. "Commissioned" is finished
            # non-AI art (artist commissions plus the handful of purchased
            # assets); a COMMISSIONED_PLACEHOLDER is not finished, so it is not.
            art_type = row.get("ArtType", "").strip()
            starter_decks = [d.strip() for d in row.get("StarterDecks", "").split(",") if d.strip()]

            cards.append({
                "name": name,
                "type": row.get("Type", "").strip(),
                "text": row.get("TextBox", "").strip(),
                "subtype": row.get("Subtype", "").strip() if row.get("Subtype", "").strip() != "None" else "",
                "cost": int(cost) if cost.isdigit() else None,
                "attack": int(attack) if attack.isdigit() else None,
                "speed": int(speed) if speed.isdigit() else None,
                "health": int(health) if health.isdigit() else None,
                "legendary": row.get("Legendary", "").strip().lower() == "true",
                "patron": patron,
                "faction": PATRON_MAP.get(patron, "neutral"),
                "art": f"CardScreenshots/{art_file}" if has_art else None,
                "art_type": art_type,
                "commissioned": art_type in COMMISSIONED_ART_TYPES,
                "has_animation": row.get("HasAnimation", "").strip().lower() == "true",
                "starter_decks": starter_decks,
                "mentions": parse_mentioned_cards(row),
                "token": token,
            })

    label = "tokens" if token else "cards"
    print(f"  Loaded {len(cards)} {label} from CSV")
    return cards


def load_tokens_csv():
    """Load generated (token) card definitions."""
    return load_cards_csv(TOKENS_CSV, token=True)


def mention_slug(name):
    """Slug used as the key of mentions.json.

    Must stay byte-identical to cardArtSlug() in site/js/shared.js and
    site/js/cardpreview.js — the frontend looks cards up by this slug, which is
    also the /assets/cards/<slug>.jpg filename.
    """
    return re.sub(r"\s+", "-", re.sub(r"[,.']", "", (name or "").lower())).strip("-")


def build_mentions_index(*record_groups):
    """Build the mentions.json payload: slug → [{name, slug}, …].

    Keyed by slug rather than name so callers holding only a slug (the Cards
    table rows, archetype tables) can look up without the canonical name. Only
    cards that actually mention something get an entry, keeping the file tiny.
    Mentioned names that resolve to nothing known are dropped — a typo in the
    CSV shouldn't render a broken image on every page.
    """
    known = {}
    for group in record_groups:
        for rec in group:
            known.setdefault(mention_slug(rec["name"]), rec["name"])

    index = {}
    for group in record_groups:
        for rec in group:
            entries = []
            for raw in rec.get("mentions", []):
                slug = mention_slug(raw)
                if slug not in known or slug == mention_slug(rec["name"]):
                    continue
                entries.append({"name": known[slug], "slug": slug})
            if entries:
                index[mention_slug(rec["name"])] = entries
    return index


def load_commanders_csv():
    """Load commander definitions from intern's CSV."""
    commanders = []
    if not COMMANDERS_CSV.exists():
        print(f"  Warning: {COMMANDERS_CSV} not found, skipping commander definitions")
        return commanders

    with open(COMMANDERS_CSV, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = normalize_commander(row.get("Name", "").strip())
            if not name:
                continue

            patron = row.get("Patron", "Neutral").strip()

            # Commander artwork slug
            art_slug = name.lower().replace(" ", "-").replace(",", "").replace("'", "")
            art_file = f"{art_slug}.jpg"
            has_art = (ASSETS_DIR / art_file).exists() if ASSETS_DIR.exists() else False

            art_type = row.get("ArtType", "").strip()

            commanders.append({
                "name": name,
                "text": row.get("TextBox", "").strip(),
                "subtype": row.get("Subtype", "").strip() if row.get("Subtype", "").strip() != "None" else "",
                "dominion": int(row.get("Dominion", 0) or 0),
                "intellect": int(row.get("Intellect", 0) or 0),
                "speed": int(row.get("Speed", 0) or 0),
                "health": int(row.get("Health", 0) or 0),
                "patron": patron,
                "faction": PATRON_MAP.get(patron, "neutral"),
                "art": f"assets/commanders/{art_file}" if has_art else None,
                "art_type": art_type,
                "commissioned": art_type in COMMISSIONED_ART_TYPES,
                "has_animation": row.get("HasAnimation", "").strip().lower() == "true",
                "mentions": parse_mentioned_cards(row),
            })

    print(f"  Loaded {len(commanders)} commanders from CSV")
    return commanders


# ─── JSON Writers ────────────────────────────────────────────────

def write_json(filename, data, compact=False):
    """Write data to a JSON file in the data directory."""
    path = DATA_DIR / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        if compact:
            json.dump(data, f, separators=(",", ":"), default=str)
        else:
            json.dump(data, f, indent=2, default=str)
    size_kb = path.stat().st_size / 1024
    print(f"  Wrote {path.name} ({size_kb:.0f} KB)")


# ─── Cache Management ────────────────────────────────────────────

def load_cache():
    """Load previously processed games from cache."""
    if not RAW_CACHE.exists():
        return [], set()

    try:
        with open(RAW_CACHE, "r") as f:
            cached = json.load(f)
        game_ids = {g["game_id"] for g in cached}
        print(f"  Loaded {len(cached)} cached games")
        return cached, game_ids
    except (json.JSONDecodeError, KeyError):
        return [], set()


def save_cache(games):
    """Save processed games to cache for incremental fetching."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(RAW_CACHE, "w") as f:
        json.dump(games, f, separators=(",", ":"))
    print(f"  Cached {len(games)} games to {RAW_CACHE.name}")
